### Test get restaurants
GET localhost:3001/restaurant

### Test register
POST localhost:3001/user/register
Content-Type: application/json

{
  "username": "tomihi",
  "password": "test"
}

### Test login

POST localhost:3001/user/login
Content-Type: application/json

{
  "username": "tomihi",
  "password": "test"
}


### Test get profile

GET localhost:3001/user/profile
Authorization: Basic tomihi test


### Test get admin

GET localhost:3001/admin
Authorization: Basic tomihi test
